apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-origin-tls
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-origin-tls
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: cloudflare-origin-cert  # The name of the secret in Azure Vault for the CRT
    - secretKey: tls.key
      remoteRef:
        key: cloudflare-origin-key   # The name of the secret in Azure Vault for the KEY
