ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
  rules:
    - host: keycloak.accentlabels.com
  tls:
   - hosts:
       - keycloak.accentlabels.com
     secretName: "keycloak-tls"
database:
  existingSecret: "postgres-creds"
  existingSecretKey: "dbpassword"
  vendor: postgres
  hostname: postgres
  port: 5432
  database: main
  username: main
extraEnv:
  - name: KC_LOG_LEVEL
    value: DEBUG
  - name: KC_HTTP_ENABLED
    value: true
  - name: KC_HOSTNAME
    value: "https://keycloak.accentlabels.com"
  - name: KC_PROXY
    value: 