name: Terraform Plan & Apply

on:
  pull_request:
    paths:
      - 'terraform/svzez-com/**'
    types: [opened, synchronize, reopened]
    branches:
      - main
  push:
    paths:
      - 'terraform/svzez-com/**'
    branches:
      - main

  workflow_dispatch:

env:
  TF_ROOT_DIR: terraform/svzez-com

permissions:
  id-token: write 
  contents: read 
  pull-requests: write 

jobs:
  terraform_plan_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }} 

      - name: Configure AWS Credentials (for Plan)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }} 
          aws-region: ca-central-1
          role-session-name: plan-session
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=${{ env.TF_ROOT_DIR }} init -reconfigure

      - name: Terraform Plan
        run: terraform -chdir=${{ env.TF_ROOT_DIR }} plan -no-color -input=false -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        if: github.ref == 'refs/heads/main'
